version: '3.1'
services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - "/var/Docker/db/data:/var/lib/mysql"
      - "/var/Docker/db/conf:/etc/mysql/conf.d"
    environment:
      MARIADB_USER: YOUR_DB_USER
      MARIADB_PASSWORD: YOUR_PASSWORD
      MYSQL_ROOT_PASSWORD: YOUR_PASSWORD
      MARIADB_INITDB_SKIP_TZINFO: "true"
      TZ: "Asia/Bangkok"

    command: |
      --event-scheduler=ON
      --skip-name-resolve
      --max-connections=1000
      --character-set-server=utf8
      --collation-server=utf8_general_ci

    restart: always
